name: caching_fetched_data_from_api_in_splash_with_cubit
description: "A new Flutter project."

publish_to: "none"

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.2

  # service
  dio: ^5.4.0

  # object equalit
  equatable: ^2.0.5

  # state management
  flutter_bloc: ^8.1.3

  # splash screen
  flutter_native_splash: ^2.3.9

  # caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # serlizable
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generator
  build_runner: ^2.4.7

  # linter
  flutter_lints: ^2.0.0

  # hive code generator
  hive_generator: ^2.0.1

flutter_native_splash:
  color: "#f0f1f2"
  image: assets/logo/logo.png
  color_dark: "#01090f"
  image_dark: assets/logo/logo.png

  android_12:
    image: assets/logo/logo.png
    icon_background_color: "#f0f1f2"
    image_dark: assets/logo/logo.png
    icon_background_color_dark: "#01090f"

  web: false

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
